name: Node.js CI

on: [push]
jobs:
  build-and-test:
    runs-on: self-hosted
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - run: yarn build
      - run: pm2 restart QasimDev