name: Node.js CI

on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn -v
      - run: yarn install
      - run: yarn build
      - run: pm2 restart QasimDev