name: Node.js CI

on: [push]
jobs:
  build:
    name: CI CD for nuxt app
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: sergioramos/yarn-actions/install@v6
        with:
          frozen-lockfile: true
      - run: pm2 restart QasimDev